### ISSUE TITLE
difference between this and craftingrecipes

### ISSUE THREAD

**Issue by z3t0** [deathcap/voxel-recipes#1]
What seems to be the difference between this and craftingrecipes?  Is this one the one that holds the recipe and the other is used to craft...  Or something like that.

**Comment by z3t0** [comment]
This seems to be a top levep api that breaks out from crafting recipes,why not just put them together

**Comment by deathcap** [comment]
They used to be but now craftingrecipes is standalone, and voxel-recipes is a plugin that provides a crafting recipe list plus also a smelting recipe map, could also provide other (non-crafting) recipe types in the future

**Comment by z3t0** [comment]
ok, so then whats crafting recipe used for? Or is it not used in voxelmetaverse anymore?
@deathcap Please reply to my issue about Infinite Inventory, I am having some trouble with eventemitters. Thanks

**Comment by deathcap** [comment]
https://github.com/deathcap/craftingrecipes has all the logic for crafting, this module "voxel-recipes" is merely a voxel-plugin to act as a centralized recipe list, for both crafting recipes (registerAmorphous, registerPositional, craft) and smelting recipes (regsiterSmelting, smelt). They're separated since craftingrecipes is not dependent on voxel.js, and can be used independently (the unit test is all command-line) without voxel.js or voxel-plugins.
